// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeohxD99ie2udPJ58QvHEGbpynQo68FEM',
    appId: '1:787478756634:web:3997c027b332b4a769c0a3',
    messagingSenderId: '787478756634',
    projectId: 'trynn-6ec80',
    authDomain: 'trynn-6ec80.firebaseapp.com',
    storageBucket: 'trynn-6ec80.appspot.com',
    measurementId: 'G-EES8NCCBVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClCBHHjt9P1eVOY4fELhe7Ymo-DlENGwA',
    appId: '1:787478756634:android:91b938117ff7404369c0a3',
    messagingSenderId: '787478756634',
    projectId: 'trynn-6ec80',
    storageBucket: 'trynn-6ec80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLoRkvz5MuwtWnTkrtu8k31gI1UkGRyyA',
    appId: '1:787478756634:ios:3f0e5e345270093c69c0a3',
    messagingSenderId: '787478756634',
    projectId: 'trynn-6ec80',
    storageBucket: 'trynn-6ec80.appspot.com',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLoRkvz5MuwtWnTkrtu8k31gI1UkGRyyA',
    appId: '1:787478756634:ios:9d727a3077f9ce6369c0a3',
    messagingSenderId: '787478756634',
    projectId: 'trynn-6ec80',
    storageBucket: 'trynn-6ec80.appspot.com',
    iosBundleId: 'com.example.fireBase.RunnerTests',
  );
}
